# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.cache/wt [current_project]
set_property parent.project_path C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/adder.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/alu.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/aludec.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/beepdiv.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/clkdiv.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/compare.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/controller.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/datapath.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/disdiv.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/display.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/dmem.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/flopenr.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/flopenrc.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/flopr.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/floprc.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/hazard.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/imem.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/maindec.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/mips.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/mux2.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/mux3.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/mux4.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/regfile.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/signext.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/sl2.v
  C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/sources_1/new/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/constrs_1/new/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files C:/Users/ECHOES/Desktop/pipeline_pj/MIPS_pipeline_32bit/MIPS_pipeline_32bit.srcs/constrs_1/new/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
